### ISSUE TITLE
Iteration 1 Feedback

### ISSUE THREAD

**Issue by kaesrel** [kwangsensei/KU-Polls#27]
* requirements.txt is written incorrectly.
  * Only the modules/packages name and version should be written in that file for example "Django>=4.1.1" not "1.Django".
* polls/admin.py does not register choice, so no choice can be added for the questions.
* No docstring in polls/models.py.

**Comment by kwangsensei** [comment]
* Fixed to Django >= 4.1.1
* Registered choice to admin.
* Added docstring for models.py.
